services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
      PGTZ: UTC
    env_file:
      - .env
    ports:
      - "127.0.0.1:5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  app:
    build: .
    ports:
      - "8086:8080"
    environment:
      DATABASE_URL: ${POSTGRES_URL}
      DATABASE_USERNAME: ${POSTGRES_USERNAME}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
      JWT_SECRET: ${JWT_SECRET}
      MINIO_URL: ${MINIO_URL:-http://minio:9000}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_AVATAR_BUCKET: ${MINIO_AVATAR_BUCKET:-avatars}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - chat-network
      - shared-minio
    extra_hosts:
      - "90.188.89.63:host-gateway"

networks:
  shared-minio:
    external: true
    name: ${MINIO_NETWORK}
  chat-network:
    driver: bridge

volumes:
  postgres_data: